# Generated by Django 4.1.5 on 2023-01-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed']},
        ),
    ]
